In [1]:
import numpy as np

In [2]:
lis=[1,2,3,4,5]
arr=np.array(lis)
print(arr)

[1 2 3 4 5]


In [3]:
arr

array([1, 2, 3, 4, 5])

In [4]:
#get the no of rows and columns
arr.shape

(5,)

In [5]:
print(arr.shape)

(5,)


In [9]:
lis1=[6,7,8,9,10]
lis2=[11,12,13,14,15]
arr1=np.array([lis,lis1,lis2])

In [10]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [11]:
arr1.shape

(3, 5)

In [12]:
#used to reshape the array
s=arr1.reshape(5,3)


In [13]:
s.shape

(5, 3)

In [14]:
#indexing
arr[1]

2

In [15]:
arr1[1:3,:3]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [16]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [31]:
arr1[1:3,1:4]

array([[ 7,  8,  9],
       [12, 13, 14]])

In [37]:
arr2=np.arange(0,13,step=3)

In [38]:
arr2

array([ 0,  3,  6,  9, 12])

In [41]:
np.linspace(1,11,30)

array([ 1.        ,  1.34482759,  1.68965517,  2.03448276,  2.37931034,
        2.72413793,  3.06896552,  3.4137931 ,  3.75862069,  4.10344828,
        4.44827586,  4.79310345,  5.13793103,  5.48275862,  5.82758621,
        6.17241379,  6.51724138,  6.86206897,  7.20689655,  7.55172414,
        7.89655172,  8.24137931,  8.5862069 ,  8.93103448,  9.27586207,
        9.62068966,  9.96551724, 10.31034483, 10.65517241, 11.        ])

In [43]:
arr[3:]=100

In [44]:
arr

array([  1,   2,   3, 100, 100])

In [45]:
arr%2==0

array([False,  True, False,  True,  True])

In [46]:
arr[arr%2==0]

array([  2, 100, 100])

In [51]:
np.ones(5,dtype=complex)

array([1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j])

In [54]:
np.random.rand(3,2)

array([[0.24534315, 0.57974547],
       [0.75141194, 0.75240254],
       [0.83229589, 0.52059932]])

In [57]:
np.random.randn(5,5)

array([[ 2.23715593, -0.61882972, -1.53910569,  0.31452654, -0.0060202 ],
       [-1.05240677,  1.37184161,  1.58531466, -1.13903756, -0.82186984],
       [-2.4492667 , -1.16666712, -0.45728792,  1.95002073,  2.78213858],
       [-0.84352057,  0.66945787, -1.13623837,  0.780115  , -0.04153486],
       [ 0.38903811,  1.35781301,  0.1018354 , -0.83572851,  0.99816739]])

In [60]:
np.random.randint(50,150,15).reshape(5,3)

array([[ 95, 129, 113],
       [ 82, 118,  53],
       [122,  83,  98],
       [100,  93,  85],
       [105,  64,  74]])

In [17]:
np.zeros_like(arr1,dtype=bool)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])